pipeline {
    agent any

    environment {
        // Define environment variables (for Terraform)
        GOOGLE_APPLICATION_CREDENTIALS = 'C:/Users/sksus/Downloads/avian-chariot-450105-b7-da7e611e5b3c.jso' 
        TF_VAR_region = 'us-central1'  // Define region for your deployment
        TF_VAR_project_id = 'avian-chariot-450105-b7' // Define your project ID
        TF_STATE_FILE = "${WORKSPACE}/terraform.tfstate"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main' , url: 'https://github.com/naveenavuladoddi/terraforn-pipeline.git'
            }
        }
    
        stage('Terraform Init') {
            steps {
                script {
                    // Initialize Terraform (to download necessary plugins, providers)
                   
                    sh 'terraform init'
                    sh "terraform init -backend-config='path=${TF_STATE_FILE}"
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    // Run `terraform plan` to see what changes will be made to the infrastructure
                    sh 'terraform plan -out=tfplan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    // Apply the Terraform configuration to create or update resources
                    // This is where Terraform actually makes changes to your cloud infrastructure
                    sh 'terraform apply -auto-approve tfplan'
                    sh "terraform apply -state=${TF_STATE_FILE}"
                }
            }
        }

        stage('Terraform Cleanup') {
            steps {
                script {
                    // Clean up (optional): remove any temporary files generated by Terraform
                    sh 'rm -rf .terraform tfplan'
                }
            }
        }
    }

    post {
        always {
            // Clean up Terraform state and lock files (if any) after the pipeline completes
            sh 'terraform state rm -lock'
        }
    }
}
